# Generated by Django 4.1.7 on 2023-03-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjaxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_url', models.CharField(max_length=200)),
                ('request_data', models.TextField()),
                ('request_method', models.CharField(max_length=10)),
                ('response_status', models.IntegerField()),
                ('response_data', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
